# Basic imports
from argparse import ArgumentParser
from subprocess import run
from sys import executable

# Importing the needed modules / files for using the suite
from utils import exit_script
import Scanners.scanner

# Script wide varaibles
interface = ""
flags = []
path = False
save = False
show = False

def handle_args():
	global scanner
	global path
	global save
	global show
	parser = ArgumentParser(
		prog="LoudMouth",
		usage="python3 %(prog)s LoudMouth.py [arguments]",
		epilog="Every conversation can be heard."
	)
	# Optional arguments
	parser.add_argument("--path", type=str, help="Path to a file used by a module")
	parser.add_argument("--save", action="store_true", help="Save the data collected or generated by a module")
	parser.add_argument("--show", action="store_true", help="Display every message generated by a module")
	arguments = parser.parse_args()
	path = arguments.path
	save = arguments.save
	show = arguments.show

# Formatting the command
def format_command(command: list[str]) -> list[str]:
	global flags
	result = command
	for flag in flags:
		result.append(flag)
	return result

if __name__ == "__main__":
	print(" _                    _ __  __             _   _")
	print("| |    ___  _   _  __| |  \\/  | ___  _   _| |_| |__")
	print("| |   / _ \\| | | |/ _` | |\\/| |/ _ \\| | | | __| '_ \\")
	print("| |__| (_) | |_| | (_| | |  | | (_) | |_| | |_| | | |")
	print("|_____\\___/ \\__,_|\\__,_|_|  |_|\\___/ \\__,_|\\__|_| |_|")
	print("Made by: That1EthicalHacker")
	# Handling arguments
	handle_args()
	if show:
		flags.append("--show")
	if save:
		flags.append("--save")
	if path:
		flags.append("--path")
		flags.append(path)
	# Main loop
	while True:
		choice = input(">").split()
		for i in range(len(choice)):
			choice[i] = choice[i].strip("\n")
		if choice[0] == "quit":
			break
		elif choice[0] == "interface":
			if len(choice) != 2:
				print("Please use this command with one interface following via space.")
				print("Example: interface wlan1")
			else:
				interface = choice[1]
		elif choice[0] == "scanner":
			if interface == "":
				print("You must set the target interface first.")
			else:
				command = [executable, "Scanners/scanner.py", interface]
				command = format_command(command)
				try:
					run(command)
				except KeyboardInterrupt:
					pass
		elif choice[0] == "help":
			print(" Command  | Result")
			print("----------+----------------------------------")
			print("  help    | This message")
			print("  quit    | Ends script")
			print("interface | Sets the interface to second word")
			print(" scanner  | Runs the scanner module")
		else:
			print("Please use \'help\' for valid commands.")
	exit_script(0, "Every conversation can be heard.")
